#! /usr/bin/python3.6

from .exceptions import CATIAApplicationException
